[package]
name = "mvx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
fs_extra = "1.3.0"
indicatif = "0.17.11"

[dev-dependencies]
tempfile = "3.10.1"
